// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuhnwdmuupstcqputgba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1aG53ZG11dXBzdGNxcHV0Z2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjkyNzEsImV4cCI6MjA2MTc0NTI3MX0.nWNBJ0lan-w_M4PZHVnuhCg7S-zZF-SH-VKK2zbxTKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);